import type { Metadata } from "next";
export const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://webrisehub.com").replace(/\/$/, "");
export const updated = "September 26, 2026";
export type ContentSection = { id: string; title: string; paragraphs?: string[]; bullets?: string[]; steps?: string[]; links?: { label: string; href: string }[] };
export type Editorial = { title: string; description: string; eyebrow: string; sections: ContentSection[] };
export function pageMetadata(title: string, description: string, path: string): Metadata {
  return { title, description, alternates: { canonical: path }, openGraph: { title: `${title} | WebRiseHub`, description, url: path, siteName: "WebRiseHub", type: "website" } };
}
export const categories = [
  { slug: "action", name: "Action", description: "Fast arena and driving games where movement and decisions matter." },
  { slug: "drawing", name: "Drawing", description: "Freehand challenges that reward observation, control, and another try." },
  { slug: "puzzle", name: "Puzzle", description: "Location and word challenges built around clues, deduction, and discovery." },
  { slug: "reaction", name: "Reaction", description: "Quick timing challenges that reward focus, rhythm, and precise input." },
  { slug: "skill", name: "Skill", description: "Practice precision and explore interactive challenges at your own pace." },
  { slug: "casual", name: "Casual", description: "Low-pressure play and interactive experiments for a different kind of break." },
] as const;
export const games = [
  { slug: "where-am-i", title: "Where Am I?", category: "Puzzle", categories: ["puzzle"], description: "Study real-world scenes, use visual clues, and pin each mystery location on the map.", duration: "5–10 min", accent: "purple", label: "Location puzzle" },
  { slug: "wild-arena", title: "Wild Arena", category: "Action", categories: ["action"], description: "Fight rival survivors, collect stronger gear, and stay ahead of the closing storm.", duration: "4–10 min", accent: "orange", label: "Survival action" },
  { slug: "cell-rush", title: "Cell Rush", category: "Casual", categories: ["casual", "action"], description: "Collect protein, grow your cell, and outmaneuver rivals in a fast arena.", duration: "2–8 min", accent: "green", label: "Arena game" },
  { slug: "word-lock", title: "Word Lock", category: "Puzzle", categories: ["puzzle"], description: "Solve a five-letter word in six attempts or play the shared daily challenge.", duration: "2–5 min", accent: "purple", label: "Word puzzle" },
  { slug: "lock-in", title: "Lock In", category: "Reaction", categories: ["reaction", "skill"], description: "Stop the moving marker inside the target and protect your growing combo.", duration: "1–3 min", accent: "green", label: "Timing challenge" },
  { slug: "circle-game", title: "Circle Game", category: "Drawing", categories: ["drawing", "skill", "casual"], description: "A circle is just the beginning. Recreate 15 shapes and discover how close your drawing really is.", duration: "1–2 min", accent: "orange", label: "Drawing challenge" },
  { slug: "build-life", title: "Build Life", category: "Casual", categories: ["casual"], description: "Turn a daily screen-time estimate into an interactive journey through days, years, and possibilities.", duration: "4–6 min", accent: "green", label: "Interactive experiment" },
  { slug: "chess", title: "Chess", category: "Skill", categories: ["skill"], description: "Play a complete chess match against the browser bot or across the same board.", duration: "3–10 min", accent: "purple", label: "Strategy game" },
  { slug: "x0-arena", title: "X0 Arena", category: "Casual", categories: ["casual", "skill"], description: "Play 3D tic-tac-toe with bot levels, shapes, and character pieces.", duration: "1–3 min", accent: "orange", label: "3D board game" },
  { slug: "getaway", title: "Getaway", category: "Reaction", categories: ["reaction", "action"], description: "Weave through traffic, outrun the police, and push your escape score higher.", duration: "2–6 min", accent: "orange", label: "Driving challenge" },
  { slug: "dont-touch-red", title: "Don't Touch Red", category: "Reaction", categories: ["reaction"], description: "Reverse direction, avoid red hazards, and survive for as long as possible.", duration: "1–3 min", accent: "purple", label: "Reaction challenge" },
  { slug: "stack", title: "Stack", category: "Reaction", categories: ["reaction", "skill"], description: "Time every drop and build the tallest colorful tower you can.", duration: "1–3 min", accent: "green", label: "Stacking challenge" },
] as const;
export type Game = typeof games[number];
export const guides: Record<string, Editorial & { faqs: { question: string; answer: string }[] }> = {
  "circle-game": {
    title: "Circle Game", eyebrow: "Drawing · Skill · Casual", description: "Draw a circle, try a new shape, and make your next attempt a little better.",
    sections: [
      { id: "about", title: "About Circle Game", paragraphs: ["Circle Game is a freehand drawing challenge built around a simple question: how closely can you recreate a shape you have just seen? Start with a circle, square, or triangle, then explore a heart, star, or more detailed outlines such as a bicycle. The 15 choices are grouped into Easy, Medium, and Hard so you can choose the amount of detail you want to tackle.", "After a short reference countdown, you draw on a blank canvas using a mouse, pen, or touchscreen. Finish when you are ready; the timer records elapsed time but does not reduce your score. Your result separates shape, size, position, and outline accuracy, making it easier to understand what to change on the next attempt. There is no account to create and no public leaderboard: the useful comparison is with your own previous drawings."] },
      { id: "how-to-play", title: "How to play", steps: ["Select Start Drawing and choose a shape, or use Today’s Challenge.", "Study the reference during the countdown. Enable Keep reference visible if you want a small guide while drawing.", "Drag on the canvas to draw. Use Undo, Redo, Clear, or the brush slider to revise your attempt.", "Select Finish Drawing to see the overall score and individual accuracy measures.", "Use the comparison overlay to inspect the mismatch, then try the shape again or choose another."] },
      { id: "controls", title: "Controls & devices", paragraphs: ["On desktop, hold the primary mouse button and drag on the canvas. A trackpad or pointer-capable stylus also works. On a supported touchscreen, draw with your finger. Tool buttons work with keyboard focus and Enter, but freehand drawing requires a pointer; there is no keyboard-only drawing mode.", "The drawing board adapts to the available space. Choose a comfortable orientation before starting a stroke and give yourself room to draw. Sound is optional and can be switched on in the drawing toolbar."] },
      { id: "scoring", title: "What your score means", paragraphs: ["The overall result is a rounded percentage calculated from four measures. Shape similarity contributes 60%, size accuracy 15%, position accuracy 10%, and outline similarity 15%. These measures compare your canvas with the selected reference; they are not an assessment of artistic ability.", "Shape and outline comparisons use normalized drawings with tolerance around the lines. Size compares the area covered by the drawings’ bounding boxes relative to their canvases. Position rewards placing your drawing near the middle of the canvas. A recognizable shape can therefore still lose points if it is very small or far from the center."] },
      { id: "tips", title: "Five ways to improve your next drawing", bullets: ["Study the overall proportions first. A wide circle will not match a round reference even if the line is smooth.", "Leave similar space above, below, and beside the shape to keep it centered.", "Match the reference’s scale; avoid a tiny sketch in one corner of the canvas.", "Use the visible reference option while learning a new shape, then try drawing from memory.", "Read the weakest metric and change one thing on your next attempt. Undo stray strokes instead of repeatedly tracing over them."] },
      { id: "daily-and-stats", title: "Daily shapes & saved results", paragraphs: ["Today’s Challenge selects a shape using your device’s local calendar date. You can attempt it as often as you like. The displayed best score is your all-time best for that shape, not a separate daily ranking.", "This browser remembers your best score, average, completed drawings, best object, and per-shape bests. Each result of 80% or more extends your drawing streak; a lower result resets it. Results are stored on this device, do not sync between browsers, and disappear if you clear this site’s storage. Share Result opens your device’s sharing options or copies the score text when supported."] },
    ],
    faqs: [
      { question: "Is Circle Game free, and do I need an account?", answer: "It is free to play here without an account or installation." },
      { question: "Can I draw shapes other than circles?", answer: "Yes. There are 15 choices across three difficulty groups, including stars, animals, and objects. Circle Game is the name of the whole drawing experience." },
      { question: "Does finishing faster improve my score?", answer: "No. The score measures drawing similarity, size, position, and outline. Elapsed time is displayed separately." },
      { question: "Why did my saved best disappear?", answer: "Results are stored in this browser. Private browsing, clearing site data, changing browser, or blocked storage can prevent a result from being retained." },
    ],
  },
  "build-life": {
    title: "Build Life", eyebrow: "Casual · Interactive experiment", description: "Explore what a few hours a day can look like over a week, a year, and a decade.",
    sections: [
      { id: "about", title: "About Build Life", paragraphs: ["Build Life is a scroll-driven experiment about the way small daily habits accumulate. Choose an estimate of your daily phone time, then move through visual scenes that translate those hours into a week, a month, a year, and a decade. Instead of chasing a high score, you explore comparisons and try alternative choices.", "The experience includes a day planner, weekly and yearly views, a physics jar, travel comparisons, and a shareable result card. Each scene offers a different way to look at the same estimate. You can change your input and see how the totals respond without connecting a phone, granting device access, or signing in. The numbers are illustrative arithmetic based on what you enter. They are not a record of your actual usage or a prediction of what your life should look like."] },
      { id: "how-to-play", title: "How to explore", steps: ["Set Daily phone hours between 0 and 12 using the slider, or choose a 2-, 4-, or 7-hour preset.", "Begin the experience and scroll down to explore the scenes.", "Try the day blocks, weekly choices, calendar, and other scene controls to compare alternatives.", "Change your daily estimate to explore a different scenario.", "Use Share result or save the result card if you want to keep your comparison."] },
      { id: "controls", title: "Controls & accessibility", paragraphs: ["Use the mouse wheel, trackpad, or a touchscreen swipe to move through the experience. Buttons and the daily-hours slider support keyboard focus; use arrow keys to adjust the slider. Some visual scenes also use pointer interaction.", "A larger screen provides more room for the detailed scenes. The main scrolling effects respect your device’s reduced-motion preference. Interactive animations remain part of some scenes, so take the experience at a pace that feels comfortable."] },
      { id: "calculations", title: "How the comparisons work", paragraphs: ["Weekly hours are your daily estimate multiplied by seven. Annual hours use 365 days, and a decade uses ten of those years. At four hours a day, that is 28 hours a week, 1,460 hours a year, and about 1.67 years across a decade when converted into full 24-hour days.", "Comparisons use fixed assumptions: for example, 2.1 hours per movie, six hours per book, and eight hours per workday. These are visual reference points, not promises that every hour of phone time could be converted directly into another activity. Work, navigation, conversations, and entertainment can all have value."] },
      { id: "tips", title: "Get more from the experiment", bullets: ["Start with an estimate you recognize rather than the largest possible number.", "Compare two nearby settings to see the effect of a modest change.", "Distinguish useful phone time from time you personally want to spend differently.", "Try one alternative in the day planner before exploring the longer-term views.", "Save a result card if you want a record; the page does not retain your session after a reload."] },
      { id: "progress", title: "Progress & sharing", paragraphs: ["Build Life has no competitive score, account, or saved progression. Inputs stay in the current page session and reset when you reload. The experience does not read your screen-time settings or send your estimate to a game server.", "Sharing is optional. Share result opens the device share sheet where available or copies text to the clipboard. Saving a card creates an image in your browser for download. Review the contents before sharing them with someone else."] },
    ],
    faqs: [
      { question: "Does Build Life measure my actual phone use?", answer: "No. It only calculates from the daily estimate you enter. It does not connect to your phone or inspect usage data." },
      { question: "Is there a winning score?", answer: "No. This is an interactive experiment rather than a competitive game. Its purpose is to help you compare scenarios." },
      { question: "Will my choices still be here next time?", answer: "Session choices reset on reload. You can save a result card to keep an image of your comparison." },
    ],
  },
};
