import { links } from "./config";
import type { Editorial } from "./editorial";
const contact = { label: "Email WebRiseHub", href: `mailto:${links.email}` };
const adsEnabled = process.env.NEXT_PUBLIC_ENABLE_ADSENSE === "true";
export const pages: Record<string, Editorial> = {
  about: { title: "A little room for play.", eyebrow: "About WebRiseHub", description: "Browser games and interactive ideas that give an ordinary break a different shape.", sections: [
    { id: "who-we-are", title: "What is WebRiseHub?", paragraphs: ["WebRiseHub is a browser-game and interactive-experience project built around quick access and curiosity. The idea is simple: open a page, understand what you can do, and start exploring. You do not need an account or an installed app to play the experiences in this collection.", "The current collection includes Circle Game, a freehand shape-matching challenge, and Build Life, an interactive experiment about how a daily time estimate accumulates. They offer different kinds of play: one invites you to improve a result, while the other invites you to test an idea."] },
    { id: "what-we-build", title: "Experiences with something to explore", paragraphs: ["WebRiseHub develops and maintains the versions of the experiences presented here. Familiar ideas—drawing shapes, comparing numbers, experimenting with choices—become interactive pages with their own controls and feedback. The site also uses third-party open-source libraries; those components remain subject to their respective licenses.", "We want each page to be useful beyond its play area. Game guides explain the actual controls, scoring, and storage behavior, while the journal explores practical tips and the thinking behind the experiences. Claims about an individual game belong in its guide, not in vague promises about the whole collection."] },
    { id: "approach", title: "Our approach", bullets: ["Start with a clear action and a small learning curve.", "Explain controls and results in language a new player can use.", "Build layouts that adapt to different screen sizes, with device-specific limitations stated in the guide.", "Use feedback to investigate issues with play, readability, and navigation.", "Keep commercial enquiries separate from game instructions and results."], paragraphs: ["Accessibility is part of that work, and there are practical limitations. Freehand drawing, for example, needs pointer input. If a control is hard to reach or an experience does not work on your device, tell us what happened so the issue can be investigated."] },
    { id: "contact", title: "Help shape what comes next", paragraphs: ["Suggestions, reproducible bug reports, and corrections are welcome. Include the game name and a short description of what you tried. For business and copyright enquiries, use the same contact address with a clear subject."], links: [{ label: "Contact WebRiseHub", href: "/contact/" }, contact] },
  ] },
  contact: { title: "Let’s hear it.", eyebrow: "Contact", description: "A game idea, a bug, a business enquiry—here’s how to reach WebRiseHub.", sections: [
    { id: "general", title: "General enquiries", paragraphs: [`Email ${links.email} for questions about WebRiseHub, its games, or the journal. This is the contact address for the site; no account is needed to get in touch.`], links: [contact] },
    { id: "feedback", title: "Game feedback & bug reports", paragraphs: ["Use the subject “Game feedback” and include the game name, page URL, browser, device, and the steps that led to the issue. Describe what you expected and what happened instead. Screenshots can help, but remove personal information first.", "Please do not send passwords, security codes, or sensitive account information. Local game results are saved in your browser, so we cannot recover a cleared best score from a server."], links: [{ label: "Send game feedback", href: `mailto:${links.email}?subject=Game%20feedback` }] },
    { id: "business", title: "Advertising & business enquiries", paragraphs: ["For sponsorship or collaboration enquiries, describe the brand, the audience you want to reach, your proposed format, and timing. Enquiring does not reserve a placement or imply acceptance of a campaign."], links: [{ label: "Advertising information", href: "/advertise/" }, { label: "Discuss a collaboration", href: `mailto:${links.email}?subject=Business%20enquiry` }] },
    { id: "copyright", title: "Copyright & content concerns", paragraphs: ["Identify the page and material you are concerned about, explain your relationship to the rights holder, and provide a way to contact you. Include enough detail to locate the issue without sending unnecessary personal records."], links: [{ label: "Report a content concern", href: `mailto:${links.email}?subject=Copyright%20or%20content%20enquiry` }] },
    { id: "privacy", title: "Privacy questions", paragraphs: ["You can use the same address to ask about information you have sent us or request its deletion. Describe the correspondence or data involved so the request can be assessed."], links: [{ label: "Read the privacy policy", href: "/privacy-policy/" }] },
  ] },
  "privacy-policy": { title: "Privacy policy", eyebrow: "Privacy & transparency", description: "How this site handles game data, correspondence, and third-party services.", sections: [
    { id: "scope", title: "Scope & contact", paragraphs: [`This policy covers WebRiseHub at webrisehub.com and the games served on this site. For questions about this policy or information you have provided, contact ${links.email}. You can play the current games without registering an account.`] },
    { id: "game-data", title: "Information used by the games", paragraphs: ["Circle Game processes drawing input in your browser. It stores a local record of scores, completed drawings, streaks, and per-shape bests under the key drawmatch.stats.v1. This record is not an online profile and is not synchronized with a WebRiseHub game server. Drawings are not uploaded by the game’s scoring code.", "Build Life uses the daily-hours estimate and choices you enter to calculate comparisons in the open page. This version does not persist those inputs after reload or read your device’s screen-time data. Choosing to share a result uses your browser or device’s sharing service; the destination you choose then handles the shared information."] },
    { id: "correspondence", title: "Email & service information", paragraphs: ["If you email us, your email address, message, and any attachments are handled to respond to the enquiry, investigate a report, or manage the conversation. Only send information needed for that purpose.", "Like other websites, the hosting and delivery services may process technical request information, such as IP address, requested URL, browser information, and timestamps, to deliver pages and protect their infrastructure. Provider-level logs and retention are controlled by those services. This version does not include a separate visitor-analytics integration such as Google Analytics."] },
    { id: "advertising", title: "Google advertising & third parties", paragraphs: [adsEnabled ? "This deployment loads Google AdSense. Google and its advertising partners may collect or receive information including IP addresses, browser and device information, identifiers, cookie data, and interactions with advertisements for ad delivery, measurement, fraud prevention, and, where permitted, personalization." : "Advertising script loading is currently disabled in this version. A Google AdSense account-verification meta tag is present; it does not itself load advertising software. If advertising is enabled, Google and its partners may process IP addresses, browser and device information, cookies or other identifiers, and ad interactions for delivery, measurement, fraud prevention, and permitted personalization.", "Google and other third parties may place or read cookies or use similar technologies when their advertising services are active. Where required, advertising choices must be collected through the configured consent-management service. This policy is a disclosure, not a substitute for that consent process."], links: [{ label: "How Google uses information from partner sites", href: "https://policies.google.com/technologies/partner-sites" }, { label: "Google privacy policy", href: "https://policies.google.com/privacy" }, { label: "Google ad settings", href: "https://myadcenter.google.com/" }] },
    { id: "choices", title: "Your choices", paragraphs: ["You can remove local game results by clearing this site’s data in your browser. Blocking storage may prevent future results from being remembered. Browser cookie controls and Google ad settings provide additional choices for their respective technologies; changing ad-personalization settings does not necessarily stop all advertising-related processing.", "Where a consent message is available, use it to review or change advertising choices. You may also contact us about personal information you have supplied, including a request to access, correct, or delete correspondence, subject to applicable requirements."] },
    { id: "retention", title: "Retention & sharing", paragraphs: ["Local game statistics remain in your browser until cleared, overwritten, or removed by browser settings. Build Life session inputs end with the page session. Correspondence may be retained while it is needed to answer or manage the enquiry and for applicable recordkeeping obligations; contact us about a particular conversation if you want it deleted.", "Hosting, email, and any enabled advertising providers handle data needed to supply their services. We do not publish your correspondence as a player profile. Provider processing may take place in countries other than your own and is subject to the provider’s terms and privacy information."] },
    { id: "children", title: "Children’s privacy", paragraphs: ["The games do not ask players to enter a name, age, or contact details to play. Children should involve a parent or guardian before sending correspondence or sharing a result externally. If you believe a child has provided personal information to us, contact us so the message can be reviewed and appropriate action taken."] },
    { id: "changes", title: "Changes to this policy", paragraphs: ["This page may be updated when the games or services change. Review the updated date when returning to the policy, particularly after changes to advertising or storage features."], links: [{ label: "Cookie policy", href: "/cookie-policy/" }, contact] },
  ] },
  "cookie-policy": { title: "Cookies & local storage", eyebrow: "Privacy & transparency", description: "What is remembered in your browser, why it is used, and how to remove it.", sections: [
    { id: "storage", title: "Game storage", paragraphs: ["Circle Game uses browser local storage, which is different from a cookie, to remember game statistics on this device. The key drawmatch.stats.v1 stores the best score, total score, completed count, best object, drawing streak, and per-shape bests. It is written after a completed drawing and read when the game opens.", "The record has no game-defined expiry. It stays until you or your browser clear it, or it is replaced by an updated result. Build Life does not use persistent browser storage for its session choices. The current site does not set a first-party visitor-analytics cookie."] },
    { id: "advertising", title: "Advertising technologies", paragraphs: [adsEnabled ? "Google AdSense is enabled in this deployment. Google and its partners may use cookies and other identifiers for advertising and measurement, subject to applicable consent choices." : "Google advertising script loading is disabled in this version, so the site does not request advertising cookies through that script. If advertising is enabled later, Google and its partners may use cookies and other identifiers subject to the applicable consent choices.", "The cookies used by an advertising service can vary with location, settings, and the advertisement. Consult the service’s information and any consent panel for the active provider list and choices."], links: [{ label: "Google’s advertising cookie information", href: "https://support.google.com/adsense/answer/7549925" }] },
    { id: "controls", title: "Managing storage", steps: ["Open your browser’s privacy or site-settings controls.", "Find stored data for webrisehub.com (or the local preview address you are using).", "Remove that site’s stored data to clear Circle Game statistics. This cannot be undone by the game.", "Use your browser’s cookie settings to manage third-party cookies and any available consent panel to review advertising choices."], paragraphs: ["Private browsing may discard data when the session ends. Blocking storage should not stop a drawing from being scored, but the result may not be available on your next visit."], links: [{ label: "Privacy policy", href: "/privacy-policy/" }, contact] },
  ] },
  terms: { title: "Terms of use", eyebrow: "Good to know", description: "The ground rules for using WebRiseHub and its browser experiences.", sections: [
    { id: "using", title: "Using WebRiseHub", paragraphs: ["These terms apply when you use this website, its games, and its editorial content. Use the site lawfully and for its intended purpose. If you do not agree to these terms, stop using the service. Parents or guardians should supervise use where appropriate.", "The currently available games are free to play in your browser. Access to a game does not transfer ownership of its code, artwork, or other protected material."] },
    { id: "permitted", title: "Permitted use & fair play", bullets: ["Play the games and use the offered sharing and download features for your own results.", "Do not interfere with availability, attempt unauthorized access, or use the site to distribute malicious material.", "Do not misrepresent results, impersonate WebRiseHub, or use automated requests in a way that disrupts the service.", "Respect other people’s rights when sending feedback or sharing material."], paragraphs: ["Access may be restricted in response to abuse or misuse. Features may change, be suspended, or be removed, including when maintenance or a technical issue requires it."] },
    { id: "ownership", title: "Intellectual property", paragraphs: ["Site branding, original content, and game material are protected where applicable. Third-party software, assets, and other contributions remain the property of their respective rights holders and are governed by their licenses. Permission to use the website is not permission to republish its content or distribute its games commercially.", "If you believe material here infringes your rights, use the copyright enquiry instructions on the contact page."] },
    { id: "results", title: "Game results & availability", paragraphs: ["Games and information are provided as available. We do not guarantee uninterrupted access, compatibility with every device, error-free operation, or the retention of locally saved results. Clearing browser data can permanently remove local scores.", "Build Life is an illustrative experiment, not a device-usage measurement or professional advice. Circle Game percentages describe a drawing comparison in that game, not a standardized test of skill."] },
    { id: "liability", title: "Responsibility & limitations", paragraphs: ["Use the site at your discretion. To the extent permitted by applicable law, WebRiseHub excludes implied warranties and liability for indirect or consequential loss arising from use or unavailability of the service. Nothing in these terms excludes rights, remedies, or liabilities that cannot lawfully be excluded."] },
    { id: "external", title: "External links & services", paragraphs: ["Links, advertisements, sharing destinations, and browser services may take you to third-party services with their own terms. A link or advertisement is not a guarantee of that provider’s claims. Review the destination before sending information or completing a transaction."] },
    { id: "updates", title: "Changes, applicable law & contact", paragraphs: ["These terms may be revised as the service changes. The updated date identifies the current version. Your use remains subject to applicable law and any mandatory consumer protections; these terms do not remove those protections.", `For questions about these terms, contact ${links.email}.`], links: [contact, { label: "Privacy policy", href: "/privacy-policy/" }] },
  ] },
  advertise: { title: "Make your brand part of the break.", eyebrow: "Advertising & disclosure", description: "Commercial enquiries, with a clear distinction between play, editorial content, and advertising.", sections: [
    { id: "enquiries", title: "Advertising with WebRiseHub", paragraphs: ["WebRiseHub welcomes enquiries about sponsorships and brand collaborations that fit the experience. Tell us about your product, proposed format, intended audience, timing, and budget range so the idea can be considered.", "Audience size, availability, pricing, and placement are discussed for each enquiry. The presence of this page is not a promise of reach or campaign performance."], links: [{ label: "Send an advertising enquiry", href: `mailto:${links.email}?subject=Advertising%20enquiry` }] },
    { id: "disclosure", title: "How commercial content is identified", paragraphs: ["Advertising placements should be labeled as advertisements, and paid collaborations should be identified as sponsored. A game’s start button, score, and instructions should remain distinct from an advertiser’s call to action. Editorial guides describe how the games work; buying a placement does not buy an undisclosed recommendation.", adsEnabled ? "Google AdSense is enabled in this deployment. Third-party advertisements may be selected by the advertising provider." : "Advertising script loading is currently disabled in this version. WebRiseHub has an AdSense account-verification tag, but that tag alone does not display ads."] },
    { id: "privacy", title: "Advertising & your privacy", paragraphs: ["If third-party advertising is enabled, providers may use cookies or other identifiers to deliver and measure advertisements. The privacy and cookie pages describe those services and available choices. Advertising links lead to third parties, whose own terms and privacy policies apply."], links: [{ label: "Privacy policy", href: "/privacy-policy/" }, { label: "Cookie policy", href: "/cookie-policy/" }] },
  ] },
};
